"""urkit init — scaffold a default config.yaml file.

Generates a commented config file with all available options so the
user can edit it for their setup.

Usage:
    urkit init                          # writes config.yaml in CWD
    urkit init --output station_a.yaml  # custom path
"""

from __future__ import annotations

import sys
from pathlib import Path

_DEFAULT_TEMPLATE = """\
# urkit config — edit and save as config.yaml
# Generated by: urkit init
#
# Load it:
#   Python:  robot = URRobot.from_config("config.yaml")
#   CLI:     urkit teach  (auto-loads config.yaml)
#   CLI:     urkit teach --config station_a.yaml

# Robot IP address (required)
robot_ip: 192.168.1.50

# Path to SQLite points database (optional, created if missing)
points_path: points.db

# Gripper preset (optional)
# Built-in: hand-e, 2f-85, 2f-140
# Digital I/O: digital
# Omit or set to none for no gripper
gripper: none

# Gripper overrides (optional)
gripper_config:
    # Physical properties (override preset defaults)
    # mass: 1.0  # kg
    # center_of_gravity: [0.0, 0.0, 0.0]  # [x, y, z] in meters
    # tcp_offset: [0.0, 0.0, 0.175, 0.0, 0.0, 0.0]  # [x, y, z, rx, ry, rz]

    # Robotiq-specific (hand-e, 2f-85, 2f-140)
    # force: 100  # grip force 0-100
    # speed: 100  # movement speed 0-100
    # max_mm: 85  # max finger travel (e.g. 85 for 2F-85)

    # Digital gripper
    # pin: 0  # digital output pin
    # close_on_high: true  # true=HIGH closes, false=LOW closes

# IK reference posture (optional)
# Set to a saved point name to prevent elbow/wrist flipping between moves
# ik_reference: home

# Default motion parameters (optional)
# default_vel: 0.5  # m/s
# default_acc: 0.3  # m/s²

# Expert mode (optional) — disable safety speed clamping in CLI
# expert_mode: false
"""


def init_command(args: object) -> None:
    """Execute the init command to scaffold a default config file.

    Args:
        args: Parsed arguments with 'output' and 'force' attributes.
    """
    output = Path(getattr(args, "output", "config.yaml") or "config.yaml")
    force = getattr(args, "force", False)

    if output.exists() and not force:
        print(f"Error: {output} already exists.")
        print("  Remove it first or use --force to overwrite.")
        sys.exit(1)

    output.write_text(_DEFAULT_TEMPLATE)
    print(f"Created {output}")
    print("Edit it with your robot IP and gripper settings, then run:")
    print("  urkit teach")
